packages = ["typer", "rich", "csv", "json", "logging", "typing", "pathlib", "math", "dataclasses"]

[[fetch]]
from = "."
to = "."
files = ["main.py"]

[[fetch]]
from = "scripts"
to = "scripts"
files = ["parser_procedure.py", "parser_entities.py", "parser_dataclasses.py"]

[[fetch]]
from = "params"
to = "params"
files = ["alphabet.json", "dialect.json", "rules_general.json", "rules_special.json", "features_typed.csv", "features_untyped.csv"]

